### ISSUE TITLE
Detecting github (and maybe other) failures

### ISSUE THREAD

**Issue by AlexDaniel** [raku-community-modules/Pastebin-Gist#5]
Yesterday github was experiencing some issues, and this is what I got once:
https://gist.github.com/Whateverable/d8844867cb88bf607903dd8566124d2f#file-result-md

Seems like this module [blindly assumes](https://github.com/zoffixznet/perl6-Pastebin-Gist/blob/ca92449b78ac505742eb2d6748061e5491f90872/lib/Pastebin/Gist.pm6#L31) that the result is going to be proper JSON. I am not sure if this is right or not, but feels like it should do something else.

**Comment by zoffixznet** [comment]
Fixed with https://github.com/zoffixznet/perl6-Pastebin-Gist/commit/1c3a24780566e71d269d5820b4c6db1ae972de88 by dying with `"Error communicating with GitHub: {.exception.message}"`.

Note that it needs `WWW` version 1.004001 which I *just* pushed.

`zef uninstall WWW; zef install https://github.com/zoffixznet/perl6-WWW/archive/master.zip`

**Comment by AlexDaniel** [comment]
Thanks. It's better now, but I'm not entirely convinced that it resolves the issue. I probably want to handle this kind of failure differently, so AdHoc exception is probably not good enough. Maybe throw ``Pastebin::Gist::X::CommunicationError``, or something like that?

*\*shrug\**

**Comment by zoffixznet** [comment]
Made it throw `Pastebin::Gist::X` in https://github.com/zoffixznet/perl6-Pastebin-Gist/commit/0615780988842092e38bebbe0ff36e74d2709254
